-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 19:42:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_acceso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_acceso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_acceso` DEFAULT CHARACTER SET utf8 ;
USE `sistema_acceso` ;

-- -----------------------------------------------------
-- Table `sistema_acceso`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_acceso`.`roles` ;

CREATE TABLE IF NOT EXISTS `sistema_acceso`.`roles` (
  `rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(100) NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_acceso`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_acceso`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `sistema_acceso`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `id_tarjeta` VARCHAR(20) NOT NULL,
  `rol` INT NOT NULL,
  `img_direccion` VARCHAR(300) NOT NULL,
  `activo` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_roles1_idx` (`rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`rol`)
    REFERENCES `sistema_acceso`.`roles` (`rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_acceso`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_acceso`.`eventos` ;

CREATE TABLE IF NOT EXISTS `sistema_acceso`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tipo_evento` VARCHAR(50) NOT NULL,
  `hora` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`user_id`)
    REFERENCES `sistema_acceso`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
