version: "3.3"
services:
  app:
    image: dasrodriguezs/sistema-acceso:latest
    links:
      - db
    ports:
      - "5010:80"
    environment:
      DB_PASS: toor
    command: [ "flask", "run" , "--host=0.0.0.0", "--port=80" ]
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: